apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      deployment_strategy: "direct"
    - name: "uat"
      deployment_strategy: "direct"
    - name: "production"
      deployment_strategy: "direct"
      remediation_strategy: "automated"
